# Site
name: 'Anna Niman'
description: 'Anna Niman'
logo: 'assets/images/anna_logo.png'
favicon: 'assets/images/anna_logo.png'
baseurl: 'https://annaniman.github.io/' #'/annaniman'
avatar: 'assets/images/anna_logo.png'
# disqus: 'demowebsite'

include: ["_pages", "gallery"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page


# Syntax
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 20
paginate_path: "/gallery/page:num"


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
